### ISSUE TITLE
Guidance clarity for A/B Options

### ISSUE THREAD

**Issue by BethFox** [Nova-Scotia-Digital-Service/service-pattern-library#13]
on this page /service-pattern-library/basic-page.html

This instruction for A/B patterns is not quite clear: 
Do not use this pattern for complex questions that requires the user to choose from obscure choices.

My initial suggestion: 
Do not use this pattern if people may have difficulty understanding the difference between options. If they cannot confidently answer, it might cause them to hesitate or abandon the service. 

Also worth considering if we also add this (maybe as another pattern?):

If it is difficult to ask a clear question you might need to break it down into a set of smaller questions or add another option to catch exceptions. For exceptions provide an option 'None of these apply to me" or 'Its complicated'. If you use a third option, it should lead people to a page that lets them provide more details or another option for service.

**Comment by connorscarolyns** [comment]
@BethFox  How does this sound...
"Do not use this pattern if people may have difficulty understanding the difference between options. If they cannot confidently answer, it might cause them to hesitate or abandon the service. 

If it is difficult to ask a clear question you might need to break it down into a set of smaller questions or add another option to catch exceptions. For example, you could provide the option 'None of these apply to me" or 'It's complicated' if needed. User research will help uncover these areas of uncertainty."

**Comment by connorscarolyns** [comment]
completed
