### ISSUE TITLE
Correction to NSCAF address lookup

### ISSUE THREAD

**Issue by dstraveller** [Nova-Scotia-Digital-Service/service-pattern-library#17]
_"An address lookup lets users specify a NS address by entering their postal code and selecting their address from a list. There is also an option to enter a street name or number."_

**Correction:** NSCAF currently does not support address search by entering a postal code or a street name only. When searching for an address, it's a must to start with a number.

**Comment by connorscarolyns** [comment]
Hey @dstraveller, can you review and let me know if this is now correct. I have also moved the postal code validation guidance down to sit with the multiple field guidance. I didn't add the 7 character restriction piece, do you think that is necessary, or should we leave that up to the developers?

**Comment by dstraveller** [comment]
_"An address lookup lets users specify a NS address by entering their street aadress."_

A little typo at the end. It should be address. 

-------------------------------------------------------------------------------------------------
_"provide a manual option for people with international addresses or addresses that are missing or not properly listed in the address lookup"_

A request should be made to GeoNova to have the missing address included in the database. In this case, a phone number or email address should be provided.

-------------------------------------------------------------------------------------------------
We may leave the field length up to the developers.

**Comment by connorscarolyns** [comment]
Thanks @dstraveller, changes have been made
