### ISSUE TITLE
Updated text for Home introduction.

### ISSUE THREAD

**Issue by BethFox** [Nova-Scotia-Digital-Service/service-pattern-library#23]
/service-pattern-library/index.html
### Prototyping

Creating a human centered service doesn't start with building a prototype. Base your prototype on meeting the needs of the people who will use the service. Ground your understanding of needs in user research with people. Use insights learned from that research to inform decision making and priorities for your service. Continue to test your ideas and prototypes with the users of your service as you work.

!-- please remove the reference to the standards / design process for now... we'll add that when we have a public link to share.

**Comment by connorscarolyns** [comment]
@BethFox Text has been updated and will be pushed with the next release
