### ISSUE TITLE
Include English and French logos

### ISSUE THREAD

**Issue by jen-young** [Nova-Scotia-Digital-Service/service-pattern-library#24]
We were working on some screen designs with a vendor and had questions about what logo should be used on the English pages vs. French page.

**Comment by connorscarolyns** [comment]
@jen-young that information can be found in the CNS pattern library. https://cns.pages.novascotia.ca/patternlab/navigation.html We are working with CNS to remove any duplicate content from our library and unify our resources to make a coherent package, I will add a link to the relevant page on the template overview page for this in our next release.
