### ISSUE TITLE
Phase Banner Privacy Guidance for feedback

### ISSUE THREAD

**Issue by BethFox** [Nova-Scotia-Digital-Service/service-pattern-library#4]
On this page: /service-pattern-library/phase-banners.html

Provide additional guidance re: privacy when collecting feedback via link.
### Suggested draft (check with Privacy)###
When collecting feedback about an service via a form, be sure that you're not collecting any personally identifiable information as part of the feedback. There should be no way to link the feedback provided to any of the information a user enters into a service.

**Comment by connorscarolyns** [comment]
done!
