### ISSUE TITLE
Code typo

### ISSUE THREAD

**Issue by jamie-benoit** [Nova-Scotia-Digital-Service/service-pattern-library#42]
Notice an extra " in the div below on the https://nova-scotia-digital-service.github.io/service-pattern-library/pages/confirmation-page.html.

<code><div class="ns-panel__heading__container ns-heading__icon" "=""></code>

Unsure if it on other pages. 

I can fix it.

**Comment by jamie-benoit** [comment]
Typo is on...

1. panel.html
2. pages\confirmation-page.html
3. pages\confirmation-page2.html

**Comment by connorscarolyns** [comment]
Hey @jamie-benoit I'm not seeing the typo, can you add a little more info?

**Comment by jamie-benoit** [comment]
the current code is 

<code><div class="ns-panel__heading__container ns-heading__icon" "=""></code>

There is an extra " before the closing tag. 

I have the code fixed but I can't promote it.
