### ISSUE TITLE
Back Link content edit

### ISSUE THREAD

**Issue by BethFox** [Nova-Scotia-Digital-Service/service-pattern-library#5]
### When not to use this component ###
Never use the back link component together with breadcrumbs. **If necessary, you should do research with your users to learn which they find more helpful in your service.**

Consider replacing with: 
Never use the back link component together with breadcrumbs. The back link is enough in most cases. If research shows breadcrumbs are more helpful in your service then use breadcrumbs without the back link.

**Comment by connorscarolyns** [comment]
@BethFox  done. will be updated with the next push.
