### ISSUE TITLE
Text font on review page not consistent with recommended input text font

### ISSUE THREAD

**Issue by dstraveller** [Nova-Scotia-Digital-Service/service-pattern-library#55]
On https://nova-scotia-digital-service.github.io/service-pattern-library/review-answers-pages.html, input field label uses font "open_sansbold",Helvetica,Arial,Tahoma,sans-serif;". However, on review page, field labels use font "open_sansregular",Helvetica,Arial,Tahoma,sans-serif" (except for the consent checkbox text).

**Comment by connorscarolyns** [comment]
Hey @dstraveller I'm not sure what labels you are referring to on the review answers page, can you show a screenshot of the issue?

**Comment by connorscarolyns** [comment]
@dstraveller Hey, can you provide an example of this issue?

**Comment by connorscarolyns** [comment]
This is fixed now
