### ISSUE TITLE
Add phone number pattern

### ISSUE THREAD

**Issue by jamie-benoit** [Nova-Scotia-Digital-Service/service-pattern-library#56]
I was looking error message for Nova Scotia Safe Check-in Form (https://traveldeclaration-dev.apps.nonprod.novascotia.ca/en/Declaration/DestinationInfo) and for the phone number it is "Your phone number must be at least 10 digits."
![image](https://user-images.githubusercontent.com/13838127/127642149-940cde12-fd2b-42f2-b278-0febd50415b7.png)

for Ticket Lottery, it is "Enter your phone number in the format of 902-123-1234."
![image](https://user-images.githubusercontent.com/13838127/127642212-cec6082f-3276-4e1f-a244-ae0d7ace3f03.png)

for Pay a Debt, it is" Invalid daytime phone number specified"
![image](https://user-images.githubusercontent.com/13838127/127642381-6756b983-baa8-474c-9157-e625b23158b6.png)

My question is...
Do we want to have a standard error message for fields phone, address, email or other fields?

**Comment by connorscarolyns** [comment]
@jamie-benoit I don't think we need to be so prescriptive, if we had a phone number pattern then we could have some solid suggestions as we do for some other pages, but we do have guidelines set out for people to help them write better messages.
https://nova-scotia-digital-service.github.io/service-pattern-library/error-message.html
https://nova-scotia-digital-service.github.io/service-pattern-library/email-address.html#error-messages

**Comment by connorscarolyns** [comment]
Let's add a phone number pattern, Use UK example as a starting point. Be sure to include guidance on errors. Consider advice on international. business, daytime contact, text message and other types of numbers @gabwhite will work on this.

**Comment by gabwhite** [comment]
updated - pull request #69 has a start on this work!

**Comment by gabwhite** [comment]
This is done and can be continuously improved!
