### ISSUE TITLE
Clarify when NOT to use Panel

### ISSUE THREAD

**Issue by BethFox** [Nova-Scotia-Digital-Service/service-pattern-library#7]
on this page:
service-pattern-library/panel.html

It's a bit unclear what is meant by the "when not to use this component"
Never use the panel component to highlight important information within body content.

If you mean that it shouldn't be mid page try phrasing like this:
Never use the panel component to highlight important information within **the** body content **of a page of information.**

Also, it might help to consider clarifying (when to use)
Use the panel component to display important information when a _transaction_ **(and/or)major action following a submit or payment action** has been completed.

**Comment by connorscarolyns** [comment]
@BethFox  Done. Added your content for when you shouldn't. and added "Use the panel component to display important information following a major action. For example, display it after a submission or payment transaction has been completed." for when you should
