### ISSUE TITLE
Error Message when the service is bilingual 

### ISSUE THREAD

**Issue by jamie-benoit** [Nova-Scotia-Digital-Service/service-pattern-library#72]
add guidance for when a service is bilingual to the [Error Message page](https://nova-scotia-digital-service.github.io/service-pattern-library/error-message.html).

**Comment by gabwhite** [comment]
Update: these are standardized French error messages 
- What ARIA tags might need to change 
- What do developers of bilingual services need to know 
- "What do consider when your service is bilingual?"

**Comment by gabwhite** [comment]
Done!
