### ISSUE TITLE
Link text for Privacy Accordian

### ISSUE THREAD

**Issue by BethFox** [Nova-Scotia-Digital-Service/service-pattern-library#8]
on this page
/service-pattern-library/privacy-notice.html

Still an ongoing discussion about the correct text for the link in the accordion. I agree with it not being "Privacy Notice"

Consider "How we're protecting your **information**" (i just think "privacy" is too vague) In this pattern it's right where you're putting in your information... so that's my best hypothesis at this point.

STILL NEEDS TESTING

**Comment by connorscarolyns** [comment]
@BethFox Done and Agreed. I plan to connect with Kathy in the new year to go over this pattern and the phase banners to be sure we are onside with privacy.
